name: 'Setup sysroot environment'
description: 'Setup a sysroot environment by downloading a precompiled toolchain.'
author: 'psyGamer'

branding:
  icon: package
  color: blue

inputs:
  toolchain:
    description: 'The name of the requested toolchain. See README for list of available toolchains.'
    required: true

outputs:
  root:
    description: 'The root directory of the installed sysroot.'
    value: ${{ steps.install.outputs.root }}
  ar:
    description: 'The archiver of the installed sysroot.'
    value: ${{ steps.install.outputs.ar }}
  as:
    description: 'The assembler of the installed sysroot.'
    value: ${{ steps.install.outputs.as }}
  cc:
    description: 'The C compiler of the installed sysroot.'
    value: ${{ steps.install.outputs.cc }}
  cxx:
    description: 'The C++ compiler of the installed sysroot.'
    value: ${{ steps.install.outputs.cxx }}
  ld:
    description: 'The linker of the installed sysroot.'
    value: ${{ steps.install.outputs.ld }}

runs:
  using: "composite"
  steps:
  - name: Determine release version
    id: determine-version
    run: |
      # The following switch case is automatically generated by the release CI.
      VERSION=$(case "${{ inputs.toolchain }}" in
        # == VERSION SWITCH BEGIN ==
        # == VERSION SWITCH END ==
        esac
      )
      echo "version=${VERSION:?}" >> $GITHUB_OUTPUT

  - name: Install toolchain
    id: install
    run: |
      curl -LO https://github.com/${{ github.repository }}/releases/download/${{ steps.determine-version.outputs.version }}/${{ inputs.toolchain }}.tar.xz
      tar -xf ${{ inputs.toolchain }}.tar.xz -C /tmp/toolchains

      SYSROOT="/tmp/toolchains/${{ inputs.toolchain }}"
      export PATH="${PATH}:${SYSROOT}/bin"

      # Overwrite default binutils with sysroot versions
      export AR="${SYSROOT}/bin/${{ inputs.toolchain }}-ar"
      export AS="${SYSROOT}/bin/${{ inputs.toolchain }}-as"
      export CC="${SYSROOT}/bin/${{ inputs.toolchain }}-cc"
      export CXX="${SYSROOT}/bin/${{ inputs.toolchain }}-c++"
      export LD="${SYSROOT}/bin/${{ inputs.toolchain }}-ld"

      # Write output variables
      echo "root=${SYSROOT}" >> $GITHUB_OUTPUT
      echo "ar=${AR}"        >> $GITHUB_OUTPUT
      echo "as=${AS}"        >> $GITHUB_OUTPUT
      echo "cc=${CC}"        >> $GITHUB_OUTPUT
      echo "cxx=${CXX}"      >> $GITHUB_OUTPUT
      echo "ld=${LD}"        >> $GITHUB_OUTPUT
