name: Publish Action

on:
  workflow_dispatch:
    inputs:
      version-tag:
        required: true
        description: 'Git tag of the release'

permissions:
  contents: write

env:
  CROSSTOOLNG_VERSION: "1.28.0"

jobs:
  setup:
    name: Setup Build Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.check-update.outputs.matrix }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          # Full checkout
          fetch-depth: 0
          fetch-tags: true

      - name: Check for updated toolchains
        shell: bash
        id: check-update
        run: |
          MATRIX=""
          NEED_COMMA=false

          for TOOLCHAIN_CONFIG in configs/*.config; do
            if ! TOOLCHAIN_VERSION=$(git describe --contains $(git rev-list -1 HEAD -- $TOOLCHAIN_CONFIG) | sed -E 's/[~^][0-9]*//g'); then
              # The toolchain was changed since the latest release; need to rebuild
              if $NEED_COMMA; then
                MATRIX+=","
              fi

              MATRIX+="\"$(basename $TOOLCHAIN_CONFIG .config)\""
              NEED_COMMA=true
            fi
          done

          echo "matrix=[${MATRIX}]" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl bison flex gperf help2man libtool-bin meson ninja-build texinfo

      - name: Install crosstool-NG
        run: |
          curl -LO http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-${{ env.CROSSTOOLNG_VERSION }}.tar.xz
          tar -xf crosstool-ng-${{ env.CROSSTOOLNG_VERSION }}.tar.xz
          cd crosstool-ng-${{ env.CROSSTOOLNG_VERSION }}

          ./configure --prefix="${{ github.workspace }}/.local"
          make install -j$(nproc)
          echo "${{ github.workspace }}/.local/bin" >> "$GITHUB_PATH"

          cd "${{ github.workspace }}"
          tar -cf crosstool-ng.tar .local

      - name: Upload crosstool-NG
        uses: actions/upload-artifact@v7
        with:
          path: crosstool-ng.tar
          archive: false

      - name: Restore cached package sources
        uses: actions/cache@v6
        with:
          path: src.tar
          key: src.tar-${{ hashFiles('.local/share/crosstool-ng/packages') }}-${{ hashFiles('configs') }}
          restore-keys: |
            src.tar-${{ hashFiles('.local/share/crosstool-ng/packages') }}-
            src.tar-

      - name: Extract cached package sources
        run: |
          tar -xvf src.tar || true
          touch stamp

      - name: Fetch package sources
        run: |
          mkdir -p src
          
          for TOOLCHAIN_CONFIG in configs/*.config; do
            cp $TOOLCHAIN_CONFIG defconfig
            ct-ng defconfig

            sed -i -e '/CT_LOG_PROGRESS_BAR/s/y$/n/' .config
            sed -i -e '/CT_LOCAL_TARBALLS_DIR/s/HOME/CT_TOP_DIR/' .config
            sed -i -e '/CT_PREFIX_DIR/s/HOME/CT_TOP_DIR/' .config
            sed -i -e 's/^.*CT_DOWNLOAD_WGET_OPTIONS.*$/CT_DOWNLOAD_WGET_OPTIONS="--tries=10 -nc --progress=dot:binary --no-use-server-timestamps"/' .config
            if ! ct-ng source CT_PREFIX=/tmp/toolchains; then
              echo "=== build.log ==="
              cat build.log || true
              exit 1
            fi
          done

          find src -type f -not -newer stamp -delete -print
          tar -cvf src.tar src

  build-toolchains:
    strategy:
      matrix:
        toolchain: ${{ fromJson(needs.setup.outputs.matrix) }}

    name: Build Toolchains (${{ matrix.toolchain }})
    runs-on: ubuntu-latest
    needs: [setup]

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl bison flex gperf help2man libtool-bin meson ninja-build texinfo
          
      - name: Download crosstool-NG
        uses: actions/download-artifact@v8
        with:
          name: crosstool-ng.tar

      - name: Install crosstool-NG
        run: |
          tar -xf crosstool-ng.tar
          echo "$(pwd)/.local/bin" >> "$GITHUB_PATH"

      - name: Download package sources
        uses: actions/cache@v6
        with:
          path: src.tar
          key: src.tar-${{ hashFiles('.local/share/crosstool-ng/packages') }}-${{ hashFiles('configs') }}

      - name: Extract cached package sources
        continue-on-error: true
        run: tar -xvf src.tar

      - name: Build toolchain
        run: |
          cp configs/${{ matrix.toolchain }}.config defconfig
          ct-ng defconfig

          sed -i -e '/CT_LOG_PROGRESS_BAR/s/y$/n/' .config
          sed -i -e '/CT_LOCAL_TARBALLS_DIR/s/HOME/CT_TOP_DIR/' .config
          sed -i -e '/CT_GLIBC_ENABLE_DEBUG/s/y$/n/' .config
          if ! ct-ng build -j12 CT_PREFIX=/tmp/toolchains; then
            echo "=== build.log ==="
            cat build.log || true
            exit 1
          fi

      - name: Package toolchain
        working-directory: /tmp/toolchains
        run: tar -cJf ${{ matrix.toolchain }}.tar.xz ${{ matrix.toolchain }}

      - name: Upload toolchain artifact
        uses: actions/upload-artifact@v7
        with:
          path: /tmp/toolchains/${{ matrix.toolchain }}.tar.xz
          archive: false

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [build-toolchains]

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          # Full checkout
          fetch-depth: 0
          fetch-tags: true

      - name: Download built toolchains
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true

      - name: Update version switch
        shell: bash
        run: |
          IDENT="        "
          VERSION_SWITCH="${IDENT}# == VERSION SWITCH BEGIN ==\n"

          for TOOLCHAIN_CONFIG in configs/*.config; do
            if ! TOOLCHAIN_VERSION=$(git describe --contains $(git rev-list -1 HEAD -- $TOOLCHAIN_CONFIG) | sed -E 's/[~^][0-9]*//g'); then
              # The toolchain was changed since the latest release; use current version
              VERSION_SWITCH+="${IDENT}\"$(basename $TOOLCHAIN_CONFIG .config)\") echo \"${{ inputs.version-tag }}\" ;;\n"
            else
              # The toolchain was unchanged since the latest release; reuse old build
              VERSION_SWITCH+="${IDENT}\"$(basename $TOOLCHAIN_CONFIG .config)\") echo \"${TOOLCHAIN_VERSION}\" ;;\n"
            fi
          done

          VERSION_SWITCH+="${IDENT}# == VERSION SWITCH END =="

          sed -i -e "/# == VERSION SWITCH BEGIN ==/,/# == VERSION SWITCH END ==/c\\${VERSION_SWITCH}" action.yml
          cat action.yml

      - name: Commit and tag release
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add action.yml
          git commit --allow-empty -m "Release ${{ inputs.version-tag }}"
          git tag "${{ inputs.version-tag }}"

          git push origin main
          git push --tags

      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "${{ inputs.version-tag }}" --generate-notes --title "${{ inputs.version-tag }}"
          gh release upload "${{ inputs.version-tag }}" *.tar.xz
